version: "3"

networks:
  ingress:
    name: proxy
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Rome'
      WEBPASSWORD: 'segreta'
    networks:
      - ingress
    volumes:
      - '/srv/docker/pihole/etc-pihole:/etc/pihole'
      - '/srv/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
