---
  - import_tasks: user.yml
  - import_tasks: essential.yml
  - import_tasks: ssh.yml
  - import_tasks: docker/docker.yml
  - import_tasks: unattended-upgrades.yml
  - import_tasks: ntp.yml
  - import_tasks: other.yml
  - import_tasks: security/firewall.yml
  - import_tasks: security/fail2ban.yml