---
- name: Install NTP
  apt: package=ntp,ntpdate state=present update_cache=yes
  tags: ntp
  
- name: Copy over the NTP configuration
  template: src=ntp.conf dest=/etc/ntp.conf
  tags: ntp
    
- name: Make sure NTP is started up
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: Open inbound NTP connections for the timelord, time giver to all
  shell: ufw allow from {{ hostvars[inventory_hostname]['ansible_' ~ ntp_netdevice]['ipv4']['network'] }}/{{ hostvars[inventory_hostname]['ansible_' ~ ntp_netdevice]['ipv4']['netmask'] }} to any port 123
  when: timelord is defined and ansible_hostname == timelord
  tags: ntp