---
- name: Disable SSH password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Disable SSH password Authentication pt2
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#ChallengeResponseAuthentication yes"
    line: "ChallengeResponseAuthentication no"

- name: Update SSH configuration to be more secure
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin {{ security_ssh_permit_root_login }}"
    - regexp: "^Port"
      line: "Port {{ security_ssh_port }}"
    - regexp: "^UseDNS"
      line: "UseDNS {{ security_ssh_usedns }}"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords {{ security_ssh_permit_empty_password }}"
    - regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication {{ security_ssh_gss_api_authentication }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding {{ security_ssh_x11_forwarding }}"
  register: sshd_config

- name: Add configured users allowed to connect over ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ security_ssh_allowed_users | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_users | length > 0
  register: sshd_config

- name: Add configured groups allowed to connect over ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowGroups'
    line: "AllowGroups {{ security_ssh_allowed_groups | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_groups | length > 0
  register: sshd_config

- name: Restart SSHD daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

#apt purge openssh-server
#rm -rf /etc/ssh (may be necessary if using apt remove)
#apt install openssh-server