version: '3.3'

networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /srv/docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    restart: always
