networks:
  proxy:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "0"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /srv/docker/prometheus:/etc/prometheus
      - /srv/docker/prometheus/data:/prometheus
