version: '3.5'

networks:
  proxy:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    #container_name:jellyfin
    user: 0:0
    networks:
      - proxy
    #network_mode: 'host'
    privileged: true
    volumes:
      - /srv/docker/jellyfin/config:/config
      - /srv/docker/jellyfin/cache:/cache
      - /mnt/radarr/movies:/media
      - /mnt/qbittorrent/downloads:/media2:ro
      - /mnt/radarr/downloadclient-downloads:/media3:ro
      - /mnt/sonarr/tvseries:/media4:ro
      - /mnt/sonarr/downloadclient-downloads:/media5:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.greyroom.net
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
