version: "3.8"

networks:
  proxy:
    external: true

services:
  wg-easy:
    environment:
      - WG_HOST=greyroom.net
      - PASSWORD=segreta
      - WG_ALLOWED_IPS=192.168.100.0/24, 10.0.0.0/8
      - WG_DEFAULT_DNS=192.168.1.254
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - /srv/docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    networks:
      - proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
