---
version: "2.1"

networks:
  proxy:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    networks:
      - proxy
    volumes:
      - /srv/docker/qbittorrent/appdata/config:/config
      - /mnt/qbittorrent/downloads:/downloads
    restart: unless-stopped
