---
version: "2.1"

networks:
  proxy:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - proxy
    volumes:
      - /srv/docker/sonarr/data:/config
      - /mnt/sonarr/tvseries:/tv
      - /mnt/sonarr/downloadclient-downloads:/downloads
    restart: unless-stopped
